# Create a NAMESPACE
---
apiVersion: v1
kind: Namespace
metadata:
  name: api-demo-namespace

# Create a POD
---
apiVersion: v1
kind: Pod
metadata:
  name: api-demo-pod
  namespace: api-demo-namespace
  labels:
    app: becode-api
spec:
  containers:
    # The container name
    - name: api-demo-container
      # The image name (from Docker Hub)
      image: <your-docker-hub-username>/api-demo:latest
      # Ensure it will always pull the image to update it when you push a new version
      imagePullPolicy: Always
      # The port to expose to the service
      ports:
        - containerPort: 80

# Create a SERVICE
---
apiVersion: v1
kind: Service
metadata:
  name: api-demo-service
  namespace: api-demo-namespace
spec:
  selector:
    # The app label we defined in the POD
    app: becode-api
  ports:
    - protocol: TCP
      # Port of the service
      port: 80
      # Port of the container
      targetPort: 80
  type: ClusterIP
